<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Ajout d'une expérience restaurant</title>
        <link href='css/stylesite.css' rel='stylesheet' type='text/css'>

    </head>
    <body id="body-form">
        <h1>Ajout d'une expérience restaurant</h1>
		
		<div class="form-div">
		
		
		<form method="get" action="/show-all">
						
			<h2>L'expérience a bien été ajoutée</h2>	
			<input type="submit" value="Retour aux expériences"  class="button"  />
		</form>		
		
		</div>
		
		

    </body>
</html>
