<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
		 <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Ajout d'une expérience restaurant</title>
		<link href="css/bootstrap/css/bootstrap.min.css" rel="stylesheet">		
        <link href='css/stylesheet2.css' rel='stylesheet' type='text/css'>
    </head>
    <body id="body-form">
        <h1>Ajout d'une expérience restaurant</h1>
		
			<div class="panel panel-warning">
		
				<div  class="panel-heading">
					<h2>Ajout réussi</h2>
				
				</div> 
				
				<div  class="panel-body">
					<button class="btn btn-lg btn-success"> <a href="/show all"> Retour aux expériences </a></button>
				</div> 
		
		
		
		</div>
		
		

    </body>
</html>
