<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Ajout d'une expérience restaurant</title>
        <link href='css/stylesite.css' rel='stylesheet' type='text/css'>

    </head>
    <body id="body-form">
        <h1>Formulaire</h1>
		
		<div class="form-div">
		
		
		<form action="/ajout-reussi" method="post" >
		
        <h2>Ajout d'une expérience au restaurant de mon choix.</h2>
		

			
			
		
		</form>
		
		
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

    </body>
</html>
