<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Expérience restaurant supprimée</title>
		<link href="../css/bootstrap/css/bootstrap.min.css" rel="stylesheet">		
        <link href='../css/stylesheet2.css' rel='stylesheet' type='text/css'>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="../css/bootstrap/js/bootstrap.min.js"></script>

    </head>
    <body >
		<h1>Suppression d'une expérience restaurant</h1>
        <?php include 'menu.phtml';?>
		<div class="round_box bg-picture">
		<div class="panel panel-warning">
		
				<div  class="panel-heading">
					<h2>L'expérience a bien été supprimée</h2>
				
				</div> 
				
				<div  class="panel-body">
					<button class="btn btn-lg btn-success"> <a href="/show-all"> Retour aux restaurants </a></button>
				</div> 
		
		
		
		</div>
		
		</div>
		
		
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

    </body>
</html>
