<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Expérience restaurant supprimée</title>
        <link href='css/stylesite.css' rel='stylesheet' type='text/css'>

    </head>
    <body >
        <h1>Expérience restaurant supprimée</h1>
		
		<div class="form-div">
		
		
		
        <h2>L'expérience a bien été supprimée</h2>
		
		
		<form method="get" action="/show-all">
							
			<input type="submit" value="Retour aux restaurants"  class="button"  />
		</form>		
		
		
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

    </body>
</html>
