<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Ajout d'une expérience restaurant</title>
        <link href='../templates/css/stylesite.css' rel='stylesheet' type='text/css'>

    </head>
    <body>
        <h1>Formulaire</h1>
		
        <h2>Ajout d'une expérience au restaurant de mon choix.</h2>
		
		
		
		
		<form action="/Ajout-Reussi" method="post" >
		
			<!-- nom -->
			<div>
				<label for="name">Nom du restaurant</label>
				<input type="text" id="name" />
			</div>
			
			
			
			<!-- localisation -->
			<div>
				<label for="location">Adresse</label>
				<input type="text" id="location" />
			</div>
			
			
			<!-- note ++ -->
			<div>
				<label for="courriel">Note</label> 
			</div>
			
			
			<!-- type ++ -->
			<div>
				<label for="message">Type</label> 
			</div>
			
			
			
			<!-- prix ++ -->
			<div>
				<label for="courriel">Prix</label> 
			</div>
			
			
			
			
			<!-- avis -->
			<div>
				<label for="review">Avis</label>
				<textarea id="review"></textarea>
			</div>
			
			<div >
				<button type="submit" class="button">Ajouter la review</button>
			</div>
			
		
		</form>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

    </body>
</html>
