<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Ajout d'une expérience restaurant</title>
        <link href='../templates/css/stylesite.css' rel='stylesheet' type='text/css'>

    </head>
    <body id="body-form">
        <h1>Formulaire</h1>
		
		<div class="form-div">
		
		
		<form action="/Ajout-Reussi" method="post" >
		
        <h2>Ajout d'une expérience au restaurant de mon choix.</h2>
		
			<!-- nom -->
			<div>
				<label for="name">Nom du restaurant</label>
				<input type="text" id="name" />
			</div>
			
			
			
			<!-- localisation -->
			<div>
				<label for="location">Adresse</label>
				<input type="text" id="location" />
			</div>
			
			
			<!-- note ++ -->
			<div>
				<label for="courriel">Note</label> 
				<div class="stars">
					<input class="star star-5" id="star-5" type="radio" name="star"/><label class="star star-5" for="star-5"  title="Excellent !"></label>
					<input class="star star-4" id="star-4" type="radio" name="star"/><label class="star star-4" for="star-4"  title="Bon"></label>
					<input class="star star-3" id="star-3" type="radio" name="star"/><label class="star star-3" for="star-3" title="Pas mal"></label>
					<input class="star star-2" id="star-2" type="radio" name="star"/><label class="star star-2" for="star-2" title="Peut mieux faire" ></label>
					<input class="star star-1" id="star-1" type="radio" name="star" checked="true"/><label class="star star-1" for="star-1" title="Nul"></label>
					 
				</div>
							
			
			</div>
			
			<!-- type ++ -->
			<div>
				<label for="message">Type de cuisine</label> <br/>
				<select>
					  <option value="africaine">Africaine</option>
					  <option value="amérique-du-nord">Amérique du Nord</option>
					  <option value="amérique-du-sud">Amérique du Sud</option>
					  <option value="chinoise">Chinoise</option>
					  <option value="espagnole">Espagnole</option>
					  <option value="europe-du-nord">Europe du Nord</option>
					  <option value="europe-de-l-est">Europe de l'Est</option>
					  <option value="française">Française</option>
					  <option value="fruits-de-mer">Fruits de mer</option>
					  <option value="gastronomique">Gastronomique</option>
					  <option value="indienne">Indienne</option>
					  <option value="italienne">Italienne</option>
					  <option value="japonnaise">Japonnaise</option>
					  <option value="orientale">Orientale</option>
				</select>
			</div>
			
			
			
			<!-- prix ++ -->
			<div>
				<label for="courriel">Prix</label> <br/>
					<div class="prices">
						<input class="price price-3" id="price-3" type="radio" name="price"/><label class="price price-3" for="price-3"  title="Cher"></label>
						<input class="price price-2" id="price-2" type="radio" name="price"/><label class="price price-2" for="price-2"  title="Moyen"></label>
						<input class="price price-1" id="price-1" type="radio" name="price"  checked="true"/><label class="price price-1" for="price-1" title="Pas cher"></label>
					</div>
							
			</div>
			
			
			
			
			<!-- avis -->
			<div>
				<label for="review">Avis</label>
				<textarea id="review"></textarea>
			</div>
			
			<div >
				<button type="submit" class="button">Ajouter la review</button>
			</div>
			
		
		</form>
		
		
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

    </body>
</html>
