<!DOCTYPE html>


<html>


    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Se connecter</title>
        <link href="css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href='css/stylesheet2.css' rel='stylesheet' type='text/css'>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="css/bootstrap/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">
    </head>
	
	
	
    <body>
		<h1>Se connecter</h1>
        <?php include 'menu.phtml';?>
		<div class="round_box bg-picture">
		<form action="/login" method="post" class="panel panel-warning" enctype="multipart/form-data">
			
			<div class = "panel-heading">
				<h2>Se connecter</h2>
				
			</div>
			
			<div class="panel-body">
			
				<!-- nom/email -->
				<div>					
					<input type="text" id="username" name="username" placeholder="Nom d'utilisateur/Email"/>
				</div>
				
				
				
				<!-- mot de passe -->
				<div>
					<input type="password" id="password" name="password"/>
				</div>
				
				<div >
					<button type="submit" class="btn btn-lg btn-success form-button">Se connecter</button>
				</div>
				
				
		</form>
		<div>
			<a href="/signup">S'enregistrer</a>
		</div>
		</div>
		
		</div>
    </body>
</html>
