<nav class="navbar ">
		  <div class="container-fluid">
		  <!--
			<div class="navbar-header">
			  <a class="navbar-brand" href="#">WebSiteName</a>
			</div> -->
			<ul class="nav navbar-nav">
			  <li class="active"><a href="/">Home</a></li>
			  <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Type de cuisine <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<?php $types=['Africaine','Amérique du Nord','Amérique du Sud','Chinoise','Espagnole',
					'Europe du Nord',"Europe de l'Est",'Française','Fruits de mer','Gastronomique','Indienne',
					'Italienne','Japonnaise','Orientale'];
					foreach($types as $type) { ?>
					<li><a href="/type/<?=str_replace("'","-",str_replace(' ','-',$type))?>"><?=$type ?></a></li>
					<?php } ?>
				</ul>
			  </li>
			  <li><a href="restaurants/by-notes">Les mieux notés</a></li>
			  <li><a href="restaurants/by-price">Les moins cher</a></li>
			</ul>
			
			<?php if ($isChecked) { ?>
			 <!-- l'utilisateur est connecté -->

			 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><?=$user->username?> <span class="caret"></span></a>
				<ul class="dropdown-menu">				
					<li><a href="#">Mon compte</a></li>
					<li><a href="#">Mes restaurants</a></li>
					<li><a href="/add">Ajouter un restaurant</a></li>
					<li><a href="/logout">Se déconnecter</a></li>
				</ul>
			  </li>
			<!--  <a href="/add"> <button class="btn btn-lg btn-success">  </button></a> -->
			<?php } else {?>
			<!-- on affiche le lien pour se connecter -->
			<div> <a href="/login">Se connecter</a></div>
			<?php } ?>
			
		  </div>