<!DOCTYPE html>
<html>


    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Afficher tout</title>
        <link href="css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href='css/stylesheet2.css' rel='stylesheet' type='text/css'>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="css/bootstrap/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">
    </head>
	
	
	
    <body>
		<h1>Toutes les reviews de restaurants</h1>

        
		<div class="round_box bg-picture">
			<div class=" panel panel-warning">
				<div class="panel-heading">
					<h2><?=$user->username?></h2>
				</div>
				<div
			</div>
		</div>
    </body>
</html>
