<!DOCTYPE html>
<html>

	<!-- 	-->
    <head>
        <meta charset="utf-8"/>
        <title>Mon experience chez...</title>
        <link href='../css/stylesite.css' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="../font-awesome-4.7.0/css/font-awesome.min.css">

    </head>
    <body>
        <h1>Mon experience chez...</h1>
		
		<div class="round_box item_resto">
		
			<?php
				
					//récupère 1 restaurant 
					
						$id = $restaurant->id;				
						$name = $restaurant->name;	
						$location = $restaurant->location;	
						$price = $restaurant->price;	
						$rating = $restaurant->rating;	
						$type = $restaurant->type;	
						$review = $restaurant->review;	
						
			?>
				
			<h2><?=$name?></h2>
			
							
							<!--Note-->
							
							<p> 
							
								<?php
									$colorMap[1] = '#fd1100'; //red
									$colorMap[2] = '#ff9622'; 
									$colorMap[3] = '#ffe13b'; 
									$colorMap[4] = '#98d786'; 
									$colorMap[5] = '#98d728'; //green 

									for ($x = 0; $x < $rating; $x++) {
										echo  "<span style=\"color: $colorMap[$rating] ;\"><i class=\"fa fa-star fa-2x\" aria-hidden=\"true\"></i></span>";
									} 
																
								?>
															
							</p>
							
							<p>Type de cuisine : <?=str_replace('-',' ',$type) ?></p>
							
							
							
							
							<p>Adresse : <?=$location ?></p>
							
							<!--Prix-->
							
							<p>Prix : 
								<?php
									$colorMap[1] = '#98d728'; //green
									$colorMap[2] = '#ffe13b'; //orange
									$colorMap[3] = '#fd1100'; //red

									for ($x = 0; $x < $price; $x++) {
										echo  "<span style=\"color: $colorMap[$price] ;\"><i class=\"fa fa-eur\" aria-hidden=\"true\"></i></span>";
									} 
																
								?>
							</p>
							
							<p>Avis : <?=$review ?></p>
							
				
							<button class="button"> <a href="/edit/<?=$id?>"> Modifier </a></button>
							<button class="button"> <a href="/show-all"> Retour aux restaurants </a></button>
							<button class="button"> <a href="/delete"> Supprimer </a></button>
							
							
							
							
							
							
					

							
		
		</div>
		
		
		
		
		
		
		
		
		

    </body>
</html>
