<!DOCTYPE html>
<html>

	<!-- 	-->
    <head>
        <meta charset="utf-8"/>
		 <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Mon experience chez...</title>
		<link href="../css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href='../css/stylesheet2.css' rel='stylesheet' type='text/css'>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="../css/bootstrap/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="../font-awesome-4.7.0/css/font-awesome.min.css">

    </head>
    <body class = "body">
	
		
        <h1>Mon experience chez...</h1>
		<?php include 'menu.phtml';?>
		<div class="panel panel-warning d-block">
		
			<?php
				
					//récupère 1 restaurant 
					
						$id = $restaurant->id;				
						$name = $restaurant->name;	
						$location = $restaurant->location;	
						$price = $restaurant->price;	
						$rating = $restaurant->rating;	
						$type = $restaurant->type;	
						$review = $restaurant->review;
						$filepath = $restaurant->filepath;
						
			?>
			
			<div class="panel-heading">			
				<h2><?=$name?></h2>
			</div>
			
			
			<div class="panel-body">
							<p>
								<img src="../<?=$filepath?>" class="img-responsive thumbnail center-block" />
							</p>
							
							<!--Note-->
							
							<p> 
							
								<?php
									$colorMap[1] = '#ffe13b'; //red
									$colorMap[2] = '#ffe13b'; 
									$colorMap[3] = '#ffe13b'; 
									$colorMap[4] = '#ffe13b'; 
									$colorMap[5] = '#ffe13b'; //green 

									for ($x = 0; $x < $rating; $x++) {
										echo  "<span style=\"color: $colorMap[$rating] ;margin-right:15px;\"><i class=\"fa fa-cutlery fa-2x\" aria-hidden=\"true\"></i></span>";
									} 
																
								?>
															
							</p>
							
							<p>Type de cuisine : <?=str_replace('-',' ',$type) ?></p>
							
							
							
							
							<p>Adresse : <?=$location ?></p>
							
							<!--Prix-->
							
							<p>Prix : 
								<?php
									$colorMap[1] = '#98d728'; //green
									$colorMap[2] = '#ffe13b'; //orange
									$colorMap[3] = '#fd1100'; //red

									for ($x = 0; $x < $price; $x++) {
										echo  "<span style=\"color: $colorMap[$price] ;\"><i class=\"fa fa-eur\" aria-hidden=\"true\"></i></span>";
									} 
																
								?>
							</p>
							
							<p>Avis : </p>
							<p> <?=$review ?></p>
							<?php if ($isChecked) {  ?>
								
								<?php if ($isFavorite) { ?>
							<button class="btn btn-lg btn-success"> <a href="/delete-favorite/<?=$id?>"> Supprimer des favoris </a></button>	
								<?php } else { ?>
							<button class="btn btn-lg btn-success"> <a href="/add-favorite/<?=$id?>"> Ajouter aux favoris </a></button>
								<?php } ?>
							<button class="btn btn-lg btn-success"> <a href="/edit/<?=$id?>"> Modifier </a></button>							
							<button class="btn btn-lg btn-success"> <a href="/delete/<?=$id?>"> Supprimer </a></button>
							<?php } ?>
							<button class="btn btn-lg btn-success"> <a href="/show-all"> Retour aux restaurants </a></button>
							
							
			
							
		
		</div>
		</div>
		<div class="panel panel-warning d-block">
			
							
			<div class="panel-heading">
				<h2> Commentaires <span class="badge"><?=$nbComments?></span> </h2>
			</div>
			
			<div class="panel-body">
				<?php foreach ($comments as $commentaire) {
					$name=$commentaire->name;
					$comment=$commentaire->comment;
					$date=$commentaire->created_at;
				?>
				<p> <?=$name?> le <?=$date?> </p>
				<p> <?=$comment?> </p>
				<?php } ?>
				<button class="btn btn-lg btn-success"> <a href="/add-comment/<?=$id?>"> Ajouter un commentaire </a></button>
				<button class="btn btn-lg btn-success"> <a href="/show-comments/<?=$id?>"> Voir tout </a></button>
			</div>
		
		</div>
		
		
		
		

    </body>
</html>
