<!DOCTYPE html>


<html>


    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Afficher tout</title>
        <link href="css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href='css/stylesheet2.css' rel='stylesheet' type='text/css'>
		
		<link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">
    </head>
	
	
	
    <body>
	
        <h1>Toutes les reviews de restaurants</h1>
		
						
		
			<a href="/add"> <button class="btn btn-lg btn-success"> Ajouter une expérience </button></a>
			
			<div class="round_box bg-picture">
		
				<?php
				
					if(count($restaurants) == 0){
				?>
						<div class="panel panel-danger" > 
							<p class="panel-heading">Vous n'avez pas encore enregistré d'expériences restaurants.</p>
						</div>
						
				<?php		
					}
					
					else{
					
						//affiche chaque item restaurant 
						foreach ($restaurants as $restaurant) {
							$id = $restaurant->id;				
							$name = $restaurant->name;	
							$location = $restaurant->location;	
							$price = $restaurant->price;	
							$rating = $restaurant->rating;	
							$type = $restaurant->type;	
							$review = $restaurant->review;	
							$filepath= $restaurant->filepath;
						
						
									
						
				?>
				
			
						<div class=" panel panel-warning"> 
						
							<div class="panel-heading">
								<h2><?=$name?></h2>
							
							</div>
							
							
							
							<!--Note-->
							<div class="panel-body">
							<p>
								<img src="<?=$filepath?>" class="img-responsive img-rounded center-block" />
							</p>
							<p> 
							
								<?php
									$colorMap[1] = '#ffe13b'; //red
									$colorMap[2] = '#ffe13b'; 
									$colorMap[3] = '#ffe13b'; //yellow
									$colorMap[4] = '#ffe13b'; 
									$colorMap[5] = '#ffe13b'; //green 

									for ($x = 0; $x < $rating; $x++) {
										echo  "<span style=\"color: $colorMap[$rating] ;margin-right:15px;\"><i class=\"fa fa-cutlery fa-2x\" aria-hidden=\"true\"></i></span>";
									} 
																
								?>
								
								
							
							
							</p>
							
							<p>Type de cuisine : <?=str_replace('-',' ',$type) ?></p>
							
							<button class="btn btn-lg btn-success "> <a href="/restaurant/<?=$id?>"> Voir </a></button>
							</div>
							
						</div>
				<?php
						
						}
					}
				?>

				
			
		
		</div>
		
		
    </body>
</html>
