<!DOCTYPE html>


<html>


    <head>
        <meta charset="utf-8"/>
        <title>Afficher tout</title>
        <link href='css/stylesite.css' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">
    </head>
	
	
	
    <body>
	
        <h1>Toutes les reviews de restaurants</h1>
		
						
		
			<button class="button"> <a href="/add"> Ajouter une expérience </a></button>
		<div class="round_box bg-picture">
		
				<?php
				
					if(count($restaurants) == 0){
				?>
						<div class="item_resto"> 
							<p>Vous n'avez pas encore enregistré d'expériences restaurants.</p>
						</div>
						
				<?php		
					}
					
					else{
					
						//affiche chaque item restaurant 
						foreach ($restaurants as $restaurant) {
							$id = $restaurant->id;				
							$name = $restaurant->name;	
							$location = $restaurant->location;	
							$price = $restaurant->price;	
							$rating = $restaurant->rating;	
							$type = $restaurant->type;	
							$review = $restaurant->review;	
							
						
						
									
						
				?>
				
			
						<div class="item_resto"> 
							<h2><?=$name?></h2>
							
							
							
							<!--Note-->
							
							<p> 
							
								<?php
									$colorMap[1] = '#fd1100'; //red
									$colorMap[2] = '#ff9622'; 
									$colorMap[3] = '#ffe13b'; 
									$colorMap[4] = '#98d786'; 
									$colorMap[5] = '#98d728'; //green 

									for ($x = 0; $x < $rating; $x++) {
										echo  "<span style=\"color: $colorMap[$rating] ;\"><i class=\"fa fa-star fa-2x\" aria-hidden=\"true\"></i></span>";
									} 
																
								?>
								
								
							
							
							</p>
							
							<p>Type de cuisine : <?=str_replace('-',' ',$type) ?></p>
							
							<button class="button"> <a href="/restaurant/<?=$id?>"> Voir </a></button>
							
							
						</div>
				<?php
						
						}
					}
				?>

				
			
		
		</div>
		
		
    </body>
</html>
