<!DOCTYPE html>


<html>


    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Afficher tout</title>
        <link href="../css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href='../css/stylesheet2.css' rel='stylesheet' type='text/css'>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="../css/bootstrap/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">
    </head>
	
	
	
    <body>
		<h1>Toutes les reviews de restaurants</h1>
		<nav class="navbar ">
		  <div class="container-fluid">
		  <!--
			<div class="navbar-header">
			  <a class="navbar-brand" href="#">WebSiteName</a>
			</div> -->
			<ul class="nav navbar-nav">
			  <li class="active"><a href="/">Home</a></li>
			  <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Type de cuisine <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<?php $types=['Africaine','Amérique du Nord','Amérique du Sud','Chinoise','Espagnole',
					'Europe du Nord',"Europe de l'Est",'Française','Fruits de mer','Gastronomique','Indienne',
					'Italienne','Japonnaise','Orientale'];
					foreach($types as $type) { ?>
					<li><a href="/type/<?=str_replace("'","-",str_replace(' ','-',$type))?>"><?=$type ?></a></li>
					<?php } ?>
				</ul>
			  </li>
			  <li><a href="restaurants/by-notes">Les mieux notés</a></li>
			  <li><a href="restaurants/by-price">Les moins cher</a></li>
			</ul>
			<a href="/add"> <button class="btn btn-lg btn-success"> Ajouter une expérience </button></a>
		  </div>
		  
		</nav>
        
		
						
		
			
			
			<div class="round_box bg-picture">
				<div class=" panel panel-warning"> 
						
							<div class="panel-heading">
								<h2> Commentaires <span class="badge"><?=$nbComments?></span> </h2>
							</div>
		
				<?php
					
						//affiche chaque commentaire 
						foreach ($commentaires as $commentaire) {
							$id = $commentaire->id;				
							$name = $commentaire->name;	
							$comment = $commentaire->comment;
							$date = $commentaire->created_at;
						
						
									
						
				?>
				
							<div class="panel-body">
								<p> <?=$name?> le <?=$date?> </p>
								<p> <?=$comment?> </p>
							</div>
							
							
				<?php
						
					
					}
				?>

				
			
		
		</div>
		
		
    </body>
</html>
