<!DOCTYPE html>


<html>


    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>S'enregistrer</title>
        <link href="css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href='css/stylesheet2.css' rel='stylesheet' type='text/css'>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="css/bootstrap/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">
    </head>
	
	
	
    <body>
		<h1>S'enregistrer</h1>
		<?php include 'menu.phtml';?>
        
		<div class="round_box bg-picture">
		<form action="/signup" method="post" class="panel panel-warning" enctype="multipart/form-data">
			
			<div class = "panel-heading">
				<h2>S'enregistrer</h2>
				
			</div>
			
			<div class="panel-body">
			
				<!-- email -->
				<label for="name">Email</label>
				<div>					
					<input type="text" id="email" name="email" placeholder="you@yourdomain.com" class="form-control"/>
				</div>
				
				<!-- email -->
				<label for="name">Nom d'utilisateur</label>
				<div>					
					<input type="text" id="username" name="username"  class="form-control"/>
				</div
				
				<!-- mot de passe -->
				<label for="name">Mot de passe</label>
				<div>
					<input type="password" id="password" name="password" class="form-control"/>
				</div>
				
				<div >
					<button type="submit" class="btn btn-lg btn-success form-button">Se connecter</button>
				</div>
				
				
		</form>
		</div>
		</div>
		
    </body>
</html>
